
export type LearningModule = {
  day: number;
  title: string;
  description: string;
  completed: boolean;
  locked: boolean;
  slug: string;
  blogUrl?: string;
  videoUrl?: string;
};

export const learningSeriesModules: LearningModule[] = [
  {
    day: 1,
    title: 'Introduction to Cybersecurity',
    description: "Define CIA Triad, watch an intro video, take notes",
    completed: true,
    locked: false,
    slug: 'introduction-to-cybersecurity',
    blogUrl: 'http://vinayak15.medium.com/%EF%B8%8F-day-1-introduction-to-cybersecurity-45-days-of-cybersecurity-with-sutrabyte-400e5131d0c5',
    videoUrl: 'https://youtu.be/fgcqDvkQkvU',
  },
  {
    day: 2,
    title: 'Networking Basics',
    description: 'Learn about IP, TCP/UDP, ports. Use Wireshark to analyze packets',
    completed: true,
    locked: false,
    slug: 'networking-basics',
    blogUrl: 'https://medium.com/@vinayak15/-45-days-of-cybersecurity-day-2-networking-basics-0d8eb8511205',
    videoUrl: 'https://youtu.be/q49oqSCYzk4',
  },
  {
    day: 3,
    title: 'OSI & TCP/IP Models',
    description: 'Draw both models, map protocols to layers',
    completed: true,
    locked: false,
    slug: 'osi-and-tcp-ip-models',
    blogUrl: 'https://vinayak15.medium.com/%EF%B8%8F-45-days-of-cybersecurity-day-3-osi-tcp-ip-models-demystified-e86fc9478282',
    videoUrl: 'https://youtu.be/ItJTrWgSlGY',
  },
  {
    day: 4,
    title: 'Subnetting & IP Addressing',
    description: 'Solve 5 subnetting problems',
    completed: true,
    locked: false,
    slug: 'subnetting-and-ip-addressing',
    blogUrl: 'https://vinayak15.medium.com/%EF%B8%8F-45-days-of-cybersecurity-day-4-subnetting-ip-addressing-made-simple-ce4e1b53bcd5',
    videoUrl: 'https://youtu.be/Yh0w1ykGKCE',
  },
  {
    day: 5,
    title: 'Operating Systems (Linux & Windows)',
    description: 'Complete levels 0-5 in Bandit',
    completed: true,
    locked: false,
    slug: 'operating-systems-linux-and-windows',
    blogUrl: 'https://vinayak15.medium.com/%EF%B8%8F-45-days-of-cybersecurity-day-5-operating-systems-linux-windows-e977374297da',
    videoUrl: 'https://youtu.be/Z37cq3fR8hk',
  },
  {
    day: 6,
    title: 'Virtualization & Labs',
    description: 'Install Kali Linux in a VM',
    completed: true,
    locked: false,
    slug: 'virtualization-and-labs',
    blogUrl: 'https://vinayak15.medium.com/%EF%B8%8F-45-days-of-cybersecurity-day-6-virtualization-cyber-labs-81c751fe5ad1',
    videoUrl: 'https://youtu.be/UOtCDqbbSxI',
  },
  {
    day: 7,
    title: 'Command Line Essentials',
    description: 'Practice 15 basic Linux/Windows commands',
    completed: true,
    locked: false,
    slug: 'command-line-essentials',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-45-days-of-cybersecurity-day-7-command-line-essentials-abd7890d03c3',
    videoUrl: 'https://youtu.be/taTsiKwzcj0',
  },
  {
    day: 8,
    title: 'Firewalls & VPNs',
    description: 'Set up a VPN (e.g., ProtonVPN free)',
    completed: true,
    locked: false,
    slug: 'firewalls-and-vpns',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-day-8-45-firewalls-vpns-your-first-line-of-cyber-defense-cc08ccab7b3e',
    videoUrl: 'https://youtu.be/3raoLp5VMyI',
  },
  {
    day: 9,
    title: 'Cybersecurity Roles & Certifications',
    description: 'Research 3 cybersecurity roles and career paths',
    completed: true,
    locked: false,
    slug: 'cybersecurity-roles-and-certifications',
    blogUrl: 'https://medium.com/@vinayak15/-day-9-of-45-cybersecurity-roles-certifications-choose-your-path-in-cyber-bca33b99f26f',
    videoUrl: 'https://youtu.be/SF7vvDDhjdw',
  },
  {
    day: 10,
    title: 'Review + Quiz',
    description: 'Make flashcards and test yourself',
    completed: true,
    locked: false,
    slug: 'review-plus-quiz',
    blogUrl: 'https://vinayak15.medium.com/%EF%B8%8F-day-10-45-review-quiz-level-up-your-cybersecurity-foundations-bb1463080c8c',
    videoUrl: 'https://youtu.be/mfJ1vvWYMyE',
  },
  {
    day: 11,
    title: 'Introduction to Ethical Hacking',
    description: 'Complete "What is Hacking?" module',
    completed: true,
    locked: false,
    slug: 'introduction-to-ethical-hacking',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-45-days-of-cybersecurity-day-11-step-into-ethical-hacking-29cfc0cddc6f',
    videoUrl: 'https://youtu.be/nYa8TlVvpGM',
  },
  {
    day: 12,
    title: 'Footprinting & Reconnaissance',
    description: 'Use `whois`, `nslookup`, `theHarvester`',
    completed: true,
    locked: false,
    slug: 'footprinting-and-reconnaissance',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-%EF%B8%8F-day-12-45-footprinting-reconnaissance-peeking-behind-the-curtain-5a136a3e0efb',
    videoUrl: 'https://youtu.be/eO2b3zniyJo',
  },
  {
    day: 13,
    title: 'Scanning & Enumeration',
    description: 'Scan a local network with `nmap`',
    completed: true,
    locked: false,
    slug: 'scanning-and-enumeration',
    blogUrl: 'https://medium.com/@vinayak15/-45-days-of-cybersecurity-day-13-scanning-enumeration-2e6c4276b5af',
    videoUrl: 'https://youtu.be/3fUpAAOnVVI',
  },
  {
    day: 14,
    title: 'Vulnerability Assessment',
    description: 'Run Nessus on a sample machine',
    completed: true,
    locked: false,
    slug: 'vulnerability-assessment',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-day-14-45-vulnerability-assessment-the-first-line-of-defense-22af9a2d50c7',
    videoUrl: 'https://youtu.be/kL7uKpIXlAU',
  },
  {
    day: 15,
    title: 'Exploitation Basics',
    description: 'Use Metasploit to exploit a known vuln',
    completed: true,
    locked: false,
    slug: 'exploitation-basics',
    blogUrl: 'https://vinayak15.medium.com/%EF%B8%8F-day-15-45-introduction-to-exploitation-metasploit-lets-get-offensive-645448795bb0',
    videoUrl: 'https://youtu.be/y820wtdTRZw',
  },
  {
    day: 16,
    title: 'Brute Forcing',
    description: 'Try `hydra` on a login page',
    completed: true,
    locked: false,
    slug: 'brute-forcing',
    blogUrl: 'https://medium.com/@vinayak15/45-days-of-cybersecurity-day-16-brute-forcing-passwords-5efbc13c950d',
    videoUrl: 'https://youtu.be/rHHK8nvSfjo',
  },
  {
    day: 17,
    title: 'Password Cracking',
    description: 'Crack a weak hash using `john` or `hashcat`',
    completed: true,
    locked: false,
    slug: 'password-cracking',
    blogUrl: 'https://vinayak15.medium.com/%EF%B8%8F-day-17-of-45-days-of-cybersecurity-7a3f976b9731',
    videoUrl: 'https://youtu.be/JQwldjcfqxM',
  },
  {
    day: 18,
    title: 'Web App Security Intro',
    description: 'Read XSS, SQLi tutorials',
    completed: true,
    locked: false,
    slug: 'web-app-security-intro',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-day-18-45-web-application-security-your-first-line-of-digital-defense-d2c1e524bc3e',
    videoUrl: 'https://youtu.be/gFQFWp4mtQw',
  },
  {
    day: 19,
    title: 'XSS & Injection Attacks',
    description: 'Complete XSS labs',
    completed: true,
    locked: false,
    slug: 'xss-and-injection-attacks',
    blogUrl: 'https://vinayak15.medium.com/-day-19-xss-injection-attacks-breaking-into-the-web-layer-e515333a2356',
    videoUrl: 'https://youtu.be/kmlyrbF81gI',
  },
  {
    day: 20,
    title: 'Broken Authentication',
    description: 'Practice labs on login bypass',
    completed: true,
    locked: false,
    slug: 'broken-authentication',
    blogUrl: 'https://medium.com/@vinayak15/day-20-45-broken-authentication-the-silent-gateway-for-hackers-6adb40c6fc12',
    videoUrl: 'https://youtu.be/FRbN7Aqixr8',
  },
  {
    day: 21,
    title: 'Capture The Flag (CTF) Basics',
    description: 'Solve 5 easy challenges',
    completed: true,
    locked: false,
    slug: 'capture-the-flag-ctf-basics',
    blogUrl: 'https://vinayak15.medium.com/%EF%B8%8F-45-days-of-cybersecurity-day-21-capture-the-flag-ctf-basics-b11992107f63',
    videoUrl: 'https://youtu.be/tj1xoomKuL0',
  },
  {
    day: 22,
    title: 'Malware Types & Delivery',
    description: 'Classify types of malware from samples',
    completed: true,
    locked: false,
    slug: 'malware-types-and-delivery',
    blogUrl: 'https://vinayak15.medium.com/day-22-45-malware-mayhem-types-tactics-how-to-stay-safe-433011713d9d',
    videoUrl: 'https://youtu.be/RLko8_4-fQI',
  },
  {
    day: 23,
    title: 'Reverse Engineering Basics',
    description: 'Try Ghidra to open a small binary',
    completed: true,
    locked: false,
    slug: 'reverse-engineering-basics',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-45-days-of-cybersecurity-day-23-reverse-engineering-basics-3fc73cbcae81',
    videoUrl: 'https://youtu.be/XUqT3LORF4s',
  },
  {
    day: 24,
    title: 'Social Engineering',
    description: 'Simulate a phishing email (safe environment)',
    completed: true,
    locked: false,
    slug: 'social-engineering',
    blogUrl: 'https://vinayak15.medium.com/45-days-of-cybersecurity-day-24-mastering-social-engineering-outsmarting-the-human-hacker-8283ecd014ba',
    videoUrl: 'https://youtu.be/GCdy_YgxlCo',
  },
  {
    day: 25,
    title: 'Review + Mini-CTF',
    description: 'Complete "Intro to Pentesting" room',
    completed: true,
    locked: false,
    slug: 'review-plus-mini-ctf',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-45-days-of-cybersecurity-day-25-review-your-first-mini-ctf-%EF%B8%8F-%EF%B8%8F-5f9c063488ab',
    videoUrl: 'https://youtu.be/eHXiK19hjT4',
  },
  {
    day: 26,
    title: 'Security Monitoring',
    description: 'Set up Wazuh or Splunk in lab',
    completed: true,
    locked: false,
    slug: 'security-monitoring',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-day-26-of-45-security-monitoring-your-cyber-guardian-angel-%EF%B8%8F-%EF%B8%8F-1f5b33ed63b4',
    videoUrl: 'https://youtu.be/ikSUkgQ9OMI',
  },
  {
    day: 27,
    title: 'Incident Response',
    description: 'Map out IR process (Preparation → Lessons Learned)',
    completed: true,
    locked: false,
    slug: 'incident-response',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-45-days-of-cybersecurity-day-27-incident-response-react-contain-recover-3cd439b11600',
    videoUrl: 'https://youtu.be/Z6C-ncLa8cM',
  },
  {
    day: 28,
    title: 'Digital Forensics',
    description: 'Extract metadata from files using `exiftool`',
    completed: true,
    locked: false,
    slug: 'digital-forensics',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-%EF%B8%8F-45-days-of-cybersecurity-day-28-digital-forensics-deep-dive-a58a5de7ed12',
    videoUrl: 'https://youtu.be/VDQwVlL0IZc',
  },
  {
    day: 29,
    title: 'Email Security & Phishing',
    description: 'Create a phishing awareness plan',
    completed: true,
    locked: false,
    slug: 'email-security-and-phishing',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-45-days-of-cybersecurity-day-29-email-security-phishing-601227f35f1b',
    videoUrl: 'https://youtu.be/4iu4QrMSnZo',
  },
  {
    day: 30,
    title: 'DNS Security',
    description: 'Test `dig`, `host`, DNS poisoning lab',
    completed: true,
    locked: false,
    slug: 'dns-security',
    blogUrl: 'https://medium.com/@vinayak15/45-days-of-cybersecurity-day-30-dns-security-d90b69b53071',
    videoUrl: 'https://youtu.be/HCQFglNYUyw',
  },
  {
    day: 31,
    title: 'Wireless Security',
    description: 'Capture WPA handshake in lab',
    completed: true,
    locked: false,
    slug: 'wireless-security',
    blogUrl: 'https://medium.com/@vinayak15/45-days-of-cybersecurity-day-31-mastering-wireless-security-in-2025-c6f9bf4364f5',
    videoUrl: 'https://youtu.be/Px-ULm4W-VY',
  },
  {
    day: 32,
    title: 'Cloud Security Fundamentals',
    description: 'Review IAM, S3 bucket permissions',
    completed: true,
    locked: false,
    slug: 'cloud-security-fundamentals',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-day-32-cloud-security-fundamentals-securing-the-invisible-fortress-915260cafd7f',
    videoUrl: 'https://youtu.be/yNGsivPdkZw',
  },
  {
    day: 33,
    title: 'Container & DevSecOps',
    description: 'Secure a basic Docker container',
    completed: true,
    locked: false,
    slug: 'container-and-devsecops',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-45-days-of-cybersecurity-day-33-mastering-container-security-devsecops-e4a58474d61d',
    videoUrl: 'https://youtu.be/QFZXv8TcRDE',
  },
  {
    day: 34,
    title: 'Zero Trust Architecture',
    description: 'Read and summarize Zero Trust principles',
    completed: true,
    locked: false,
    slug: 'zero-trust-architecture',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-day-34-45-zero-trust-architecture-securing-every-click-every-time-7ed685d476a2',
    videoUrl: 'https://youtu.be/vM-70pTcCe8',
  },
  {
    day: 35,
    title: 'Threat Intelligence',
    description: 'Explore Indicators of Compromise (IOCs)',
    completed: true,
    locked: false,
    slug: 'threat-intelligence',
    blogUrl: 'https://medium.com/@vinayak15/45-days-of-cybersecurity-day-35-dive-into-threat-intelligence-e282d743b79b',
    videoUrl: 'https://youtu.be/2QJK6JnxJEA',
  },
  {
    day: 36,
    title: 'Advanced Malware Analysis',
    description: 'Analyze static/dynamic behavior',
    completed: true,
    locked: false,
    slug: 'advanced-malware-analysis',
    blogUrl: 'https://vinayak15.medium.com/45-days-of-cybersecurity-day-36-advanced-malware-analysis-aa1f4760f24d',
    videoUrl: 'https://youtu.be/mQsbkdqifWM',
  },
  {
    day: 37,
    title: 'Bug Bounty Basics',
    description: 'Create an account on Bugcrowd/HackerOne',
    completed: true,
    locked: false,
    slug: 'bug-bounty-basics',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-day-37-45-bug-bounty-basics-your-gateway-to-ethical-hacking-real-rewards-ce561a0091ac',
    videoUrl: 'https://youtu.be/QJxon53F4Ro',
  },
  {
    day: 38,
    title: 'Blue Team vs Red Team',
    description: 'Choose and explore one challenge',
    completed: true,
    locked: false,
    slug: 'blue-team-vs-red-team',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-day-38-45-red-team-vs-blue-team-cyber-battles-behind-the-scenes-%EF%B8%8F-23c78237b01f',
    videoUrl: 'https://youtu.be/WYmB6xvotYQ',
  },
  {
    day: 39,
    title: 'Security Policies & Compliance',
    description: 'Draft a simple security policy',
    completed: true,
    locked: false,
    slug: 'security-policies-and-compliance',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-45-days-of-cybersecurity-day-39-security-policies-compliance-26335f863ae5',
    videoUrl: 'https://youtu.be/Ar7ZYMe2UV8',
  },
  {
    day: 40,
    title: 'Privacy, GDPR, HIPAA',
    description: 'Learn the basics of GDPR, CCPA',
    completed: true,
    locked: false,
    slug: 'privacy-gdpr-hipaa',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-45-days-of-cybersecurity-day-40-privacy-gdpr-hipaa-4b3255f89519',
    videoUrl: 'https://youtu.be/qYarlbRe9zM',
  },
  {
    day: 41,
    title: 'Career Planning',
    description: 'Make a cybersecurity resume',
    completed: true,
    locked: false,
    slug: 'career-planning',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-45-days-of-cybersecurity-day-41-cybersecurity-career-planning-masterclass-29fe1911967d',
    videoUrl: 'https://youtu.be/ZapaDwsWzSw',
  },
  {
    day: 42,
    title: 'Certifications Deep Dive',
    description: 'Compare Security+, CEH, OSCP, CISSP',
    completed: true,
    locked: false,
    slug: 'certifications-deep-dive',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-45-days-of-cybersecurity-day-42-certifications-deep-dive-interactive-edition-4ee3cc317e15',
    videoUrl: 'https://youtu.be/gaGLxCUXkAU',
  },
  {
    day: 43,
    title: 'Create a Portfolio',
    description: 'Upload CTF writeups or labs',
    completed: true,
    locked: false,
    slug: 'create-a-portfolio',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-45-days-of-cybersecurity-day-43-create-a-portfolio-interactive-edition-dccc7c0148e4',
    videoUrl: 'https://youtu.be/bt52EBQc_Pk',
  },
  {
    day: 44,
    title: 'Mock Interview + Resume Review',
    description: 'Do a mock interview with a friend or mentor',
    completed: true,
    locked: false,
    slug: 'mock-interview-plus-resume-review',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-45-days-of-cybersecurity-day-44-mock-interview-resume-review-7a97e2439748',
    videoUrl: 'https://youtu.be/9rUW2eWOKTE',
  },
  {
    day: 45,
    title: 'Final Review & Goal Setting',
    description: 'Write your future plan, reflect on your 45-day journey',
    completed: true,
    locked: false,
    slug: 'final-review-and-goal-setting',
    blogUrl: 'https://medium.com/@vinayak15/%EF%B8%8F-day-45-45-the-grand-finale-reflect-celebrate-plan-your-cybersecurity-future-7a58e1b39759',
    videoUrl: 'https://youtu.be/ZrxWhSyYzdI',
  },
];
